### ISSUE TITLE
No errors for inserts

### ISSUE THREAD

**Issue by maxpain** [depyronick/clickhouse-client#17]
Hello. How to get error from ClickHouse during `INSERT`?

`Error: Request failed with status code 400`

**Comment by depyronick** [comment]
What have you tried so far?

**Comment by KeHuangT** [comment]
I have the same problem

**Comment by depyronick** [comment]
@maxpain @KeHuangT 

Can you please share the code on how you are trying to catch errors?

**Comment by ApurvGpt** [comment]
I also faced this issue. I was trying to insert an ISO format date in a DateTime column. There was a generic axios error - 'Error: Request failed with status code 400' . It took me a while to figure out the real error.

**Comment by depyronick** [comment]
@ApurvGpt @maxpain @KeHuangT 

should be fixed
