### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by philkunz** [depyronick/clickhouse-client#18]
Monitoring revealed that there seems to be a memory leak somewhere in here. Have you monitored your services over longer periods of time?

**Comment by depyronick** [comment]
hi @philkunz,

where do you experience the issue? on clickhouse, or the nodejs application that you're using the client with?

**Comment by philkunz** [comment]
node.js. -> I have a grafana dashboard showing me memory usage and cpu usage of our services. After integrating this package I noticed a steady increase in both CPU and Memory usage. I looked into the source code and noticed you are using brotli. There are other issues on Github (like here https://github.com/Alorel/shrink-ray/issues/49) where Brotli is potentially responsible for memory leaks.

**Comment by philkunz** [comment]
I reimplemented the http client quickly, and the service is not showing any memory leaks with that:
https://gitlab.com/pushrocks/smartclickhouse/-/blob/master/ts/smartclickhouse.classes.httpclient.ts

**Comment by depyronick** [comment]
Have you tried explicitly settings the `compression` option to `ClickHouseCompressionMethod.GZIP` to see if it makes any change?

**Comment by depyronick** [comment]
Please try 2.0.0 and reopen the issue if still occurs.
